version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: my-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev